### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ghchoi0427** [ghchoi0427/foy#1]
- [ ] 이력 데이터 저장
- [ ] 프론트 개선(Vue.js)
- [ ] 배치 작업
- [ ] Tapo 화면 조회
- [ ] 보안
